### PR TITLE
 Make loading accept parameter

### PR DESCRIPTION
**Pull request by rvcas**
@jihchi mind if I keep this PR open to track as you go? Since you already started lets bring the changes in from the fork once you are done but I'll add you right now as a collaborate so in the future you can push at will.

### CODE REVIEW

**Comment by jihchi** [comment]
@lrosa007 Thank you! I'm still working on this PR. I'll let you know when I'm done.

**Comment by rvcas** [comment]
@jihchi no rush at all. thank you

**Comment by jihchi** [comment]
Hi @lrosa007 , I've finished this PR, could you help for reviewing? thanks.

**Comment by rvcas** [comment]
@jihchi I will take a look tonight. Thanks ❤️

**Comment by rvcas** [comment]
actually I just went over it looks good. I'll merge it and release a new version

**Pull request merged**
